// Code generated by protoc-gen-sample. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package enum

// カードのレアリティ
type CardRarity int32

const (
	// Unknown
	CardRarity_Unknown CardRarity = 0
	// R
	CardRarity_R CardRarity = 1
	// SR
	CardRarity_SR CardRarity = 2
	// SSR
	CardRarity_SSR CardRarity = 3
)
