// Code generated by protoc-gen-sample. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package servercache

import (
	"time"

	"github.com/hikyaru-suzuki/go-con-2022-spring-sample/pkg/domain/enum"
)

// Card カード
type Card struct {
	// カードID
	ID string
	// キャラクターID
	CharacterID string
	// 名前
	Name string
	// レアリティ
	Rarity enum.CardRarity
	// 所持スキル一覧
	Skills Card_SkillSlice
	// 公開日
	PublishTime time.Time
	// スキルパワー調整用係数
	SkillCoefficient int32
}

type CardSlice []*Card

// Card_Skill スキル
type Card_Skill struct {
	// スキルID
	SkillID string
	// スキル発動条件ID
	SkillConditionID string
}

type Card_SkillSlice []*Card_Skill
