// Code generated by protoc-gen-sample. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package servercache

// Character キャラクター
type Character struct {
	// キャラクターID
	ID string
	// 名前
	Name string
}

type CharacterSlice []*Character
