// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: server/options/master/options.proto

package master

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageOption_AccessorType int32

const (
	MessageOption_Unknown        MessageOption_AccessorType = 0
	MessageOption_All            MessageOption_AccessorType = 1
	MessageOption_OnlyAdmin      MessageOption_AccessorType = 2
	MessageOption_OnlyServer     MessageOption_AccessorType = 3
	MessageOption_AdminAndServer MessageOption_AccessorType = 4
	MessageOption_AdminAndClient MessageOption_AccessorType = 5
)

// Enum value maps for MessageOption_AccessorType.
var (
	MessageOption_AccessorType_name = map[int32]string{
		0: "Unknown",
		1: "All",
		2: "OnlyAdmin",
		3: "OnlyServer",
		4: "AdminAndServer",
		5: "AdminAndClient",
	}
	MessageOption_AccessorType_value = map[string]int32{
		"Unknown":        0,
		"All":            1,
		"OnlyAdmin":      2,
		"OnlyServer":     3,
		"AdminAndServer": 4,
		"AdminAndClient": 5,
	}
)

func (x MessageOption_AccessorType) Enum() *MessageOption_AccessorType {
	p := new(MessageOption_AccessorType)
	*p = x
	return p
}

func (x MessageOption_AccessorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageOption_AccessorType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_options_master_options_proto_enumTypes[0].Descriptor()
}

func (MessageOption_AccessorType) Type() protoreflect.EnumType {
	return &file_server_options_master_options_proto_enumTypes[0]
}

func (x MessageOption_AccessorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageOption_AccessorType.Descriptor instead.
func (MessageOption_AccessorType) EnumDescriptor() ([]byte, []int) {
	return file_server_options_master_options_proto_rawDescGZIP(), []int{0, 0}
}

type FieldOption_AccessorType int32

const (
	FieldOption_All             FieldOption_AccessorType = 0
	FieldOption_OnlyAdmin       FieldOption_AccessorType = 1
	FieldOption_OnlyServer      FieldOption_AccessorType = 2
	FieldOption_OnlyClient      FieldOption_AccessorType = 3
	FieldOption_AdminAndServer  FieldOption_AccessorType = 4
	FieldOption_AdminAndClient  FieldOption_AccessorType = 5
	FieldOption_ServerAndClient FieldOption_AccessorType = 6
)

// Enum value maps for FieldOption_AccessorType.
var (
	FieldOption_AccessorType_name = map[int32]string{
		0: "All",
		1: "OnlyAdmin",
		2: "OnlyServer",
		3: "OnlyClient",
		4: "AdminAndServer",
		5: "AdminAndClient",
		6: "ServerAndClient",
	}
	FieldOption_AccessorType_value = map[string]int32{
		"All":             0,
		"OnlyAdmin":       1,
		"OnlyServer":      2,
		"OnlyClient":      3,
		"AdminAndServer":  4,
		"AdminAndClient":  5,
		"ServerAndClient": 6,
	}
)

func (x FieldOption_AccessorType) Enum() *FieldOption_AccessorType {
	p := new(FieldOption_AccessorType)
	*p = x
	return p
}

func (x FieldOption_AccessorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldOption_AccessorType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_options_master_options_proto_enumTypes[1].Descriptor()
}

func (FieldOption_AccessorType) Type() protoreflect.EnumType {
	return &file_server_options_master_options_proto_enumTypes[1]
}

func (x FieldOption_AccessorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldOption_AccessorType.Descriptor instead.
func (FieldOption_AccessorType) EnumDescriptor() ([]byte, []int) {
	return file_server_options_master_options_proto_rawDescGZIP(), []int{1, 0}
}

type MessageOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessorType MessageOption_AccessorType `protobuf:"varint,1,opt,name=accessor_type,json=accessorType,proto3,enum=server.options.master.MessageOption_AccessorType" json:"accessor_type,omitempty"`
	Ddl          *MessageOption_DDL         `protobuf:"bytes,2,opt,name=ddl,proto3" json:"ddl,omitempty"`
}

func (x *MessageOption) Reset() {
	*x = MessageOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_options_master_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOption) ProtoMessage() {}

func (x *MessageOption) ProtoReflect() protoreflect.Message {
	mi := &file_server_options_master_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOption.ProtoReflect.Descriptor instead.
func (*MessageOption) Descriptor() ([]byte, []int) {
	return file_server_options_master_options_proto_rawDescGZIP(), []int{0}
}

func (x *MessageOption) GetAccessorType() MessageOption_AccessorType {
	if x != nil {
		return x.AccessorType
	}
	return MessageOption_Unknown
}

func (x *MessageOption) GetDdl() *MessageOption_DDL {
	if x != nil {
		return x.Ddl
	}
	return nil
}

type FieldOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessorType FieldOption_AccessorType  `protobuf:"varint,1,opt,name=accessor_type,json=accessorType,proto3,enum=server.options.master.FieldOption_AccessorType" json:"accessor_type,omitempty"`
	Ddl          *FieldOption_DDL          `protobuf:"bytes,2,opt,name=ddl,proto3" json:"ddl,omitempty"`
	Validations  []*FieldOption_Validation `protobuf:"bytes,3,rep,name=validations,proto3" json:"validations,omitempty"`
}

func (x *FieldOption) Reset() {
	*x = FieldOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_options_master_options_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOption) ProtoMessage() {}

func (x *FieldOption) ProtoReflect() protoreflect.Message {
	mi := &file_server_options_master_options_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOption.ProtoReflect.Descriptor instead.
func (*FieldOption) Descriptor() ([]byte, []int) {
	return file_server_options_master_options_proto_rawDescGZIP(), []int{1}
}

func (x *FieldOption) GetAccessorType() FieldOption_AccessorType {
	if x != nil {
		return x.AccessorType
	}
	return FieldOption_All
}

func (x *FieldOption) GetDdl() *FieldOption_DDL {
	if x != nil {
		return x.Ddl
	}
	return nil
}

func (x *FieldOption) GetValidations() []*FieldOption_Validation {
	if x != nil {
		return x.Validations
	}
	return nil
}

type MessageOption_DDL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Indexes []*MessageOption_DDL_Index `protobuf:"bytes,1,rep,name=indexes,proto3" json:"indexes,omitempty"`
}

func (x *MessageOption_DDL) Reset() {
	*x = MessageOption_DDL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_options_master_options_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageOption_DDL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOption_DDL) ProtoMessage() {}

func (x *MessageOption_DDL) ProtoReflect() protoreflect.Message {
	mi := &file_server_options_master_options_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOption_DDL.ProtoReflect.Descriptor instead.
func (*MessageOption_DDL) Descriptor() ([]byte, []int) {
	return file_server_options_master_options_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MessageOption_DDL) GetIndexes() []*MessageOption_DDL_Index {
	if x != nil {
		return x.Indexes
	}
	return nil
}

type MessageOption_DDL_Index struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *MessageOption_DDL_Index) Reset() {
	*x = MessageOption_DDL_Index{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_options_master_options_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageOption_DDL_Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOption_DDL_Index) ProtoMessage() {}

func (x *MessageOption_DDL_Index) ProtoReflect() protoreflect.Message {
	mi := &file_server_options_master_options_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOption_DDL_Index.ProtoReflect.Descriptor instead.
func (*MessageOption_DDL_Index) Descriptor() ([]byte, []int) {
	return file_server_options_master_options_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *MessageOption_DDL_Index) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type FieldOption_DDL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pk       bool                `protobuf:"varint,1,opt,name=pk,proto3" json:"pk,omitempty"`
	Fk       *FieldOption_DDL_FK `protobuf:"bytes,2,opt,name=fk,proto3" json:"fk,omitempty"`
	Size     uint32              `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Nullable bool                `protobuf:"varint,4,opt,name=nullable,proto3" json:"nullable,omitempty"`
}

func (x *FieldOption_DDL) Reset() {
	*x = FieldOption_DDL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_options_master_options_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldOption_DDL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOption_DDL) ProtoMessage() {}

func (x *FieldOption_DDL) ProtoReflect() protoreflect.Message {
	mi := &file_server_options_master_options_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOption_DDL.ProtoReflect.Descriptor instead.
func (*FieldOption_DDL) Descriptor() ([]byte, []int) {
	return file_server_options_master_options_proto_rawDescGZIP(), []int{1, 0}
}

func (x *FieldOption_DDL) GetPk() bool {
	if x != nil {
		return x.Pk
	}
	return false
}

func (x *FieldOption_DDL) GetFk() *FieldOption_DDL_FK {
	if x != nil {
		return x.Fk
	}
	return nil
}

func (x *FieldOption_DDL) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FieldOption_DDL) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

type FieldOption_Validation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *FieldOption_Validation) Reset() {
	*x = FieldOption_Validation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_options_master_options_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldOption_Validation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOption_Validation) ProtoMessage() {}

func (x *FieldOption_Validation) ProtoReflect() protoreflect.Message {
	mi := &file_server_options_master_options_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOption_Validation.ProtoReflect.Descriptor instead.
func (*FieldOption_Validation) Descriptor() ([]byte, []int) {
	return file_server_options_master_options_proto_rawDescGZIP(), []int{1, 1}
}

func (x *FieldOption_Validation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FieldOption_Validation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type FieldOption_DDL_FK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table         string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Column        string   `protobuf:"bytes,2,opt,name=column,proto3" json:"column,omitempty"`
	ParentColumns []string `protobuf:"bytes,3,rep,name=parentColumns,proto3" json:"parentColumns,omitempty"`
}

func (x *FieldOption_DDL_FK) Reset() {
	*x = FieldOption_DDL_FK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_options_master_options_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldOption_DDL_FK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOption_DDL_FK) ProtoMessage() {}

func (x *FieldOption_DDL_FK) ProtoReflect() protoreflect.Message {
	mi := &file_server_options_master_options_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOption_DDL_FK.ProtoReflect.Descriptor instead.
func (*FieldOption_DDL_FK) Descriptor() ([]byte, []int) {
	return file_server_options_master_options_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *FieldOption_DDL_FK) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *FieldOption_DDL_FK) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *FieldOption_DDL_FK) GetParentColumns() []string {
	if x != nil {
		return x.ParentColumns
	}
	return nil
}

var file_server_options_master_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOption)(nil),
		Field:         52001,
		Name:          "server.options.master.message",
		Tag:           "bytes,52001,opt,name=message",
		Filename:      "server/options/master/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOption)(nil),
		Field:         52002,
		Name:          "server.options.master.field",
		Tag:           "bytes,52002,opt,name=field",
		Filename:      "server/options/master/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional server.options.master.MessageOption message = 52001;
	E_Message = &file_server_options_master_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional server.options.master.FieldOption field = 52002;
	E_Field = &file_server_options_master_options_proto_extTypes[1]
)

var File_server_options_master_options_proto protoreflect.FileDescriptor

var file_server_options_master_options_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x1a, 0x20, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfe,
	0x02, 0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x56, 0x0a, 0x0d, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x31, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3a, 0x0a, 0x03, 0x64, 0x64, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x44, 0x4c, 0x52,
	0x03, 0x64, 0x64, 0x6c, 0x1a, 0x6c, 0x0a, 0x03, 0x44, 0x44, 0x4c, 0x12, 0x48, 0x0a, 0x07, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x44, 0x44, 0x4c, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x07, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x65, 0x73, 0x1a, 0x1b, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12,
	0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65,
	0x79, 0x73, 0x22, 0x6b, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12,
	0x07, 0x0a, 0x03, 0x41, 0x6c, 0x6c, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x6e, 0x6c, 0x79,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4f, 0x6e, 0x6c, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x41, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x41, 0x6e, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x10, 0x05, 0x22,
	0x87, 0x05, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x54, 0x0a, 0x0d, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x03, 0x64, 0x64, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x44, 0x4c, 0x52, 0x03, 0x64, 0x64, 0x6c, 0x12,
	0x4f, 0x0a, 0x0b, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x1a, 0xda, 0x01, 0x0a, 0x03, 0x44, 0x44, 0x4c, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x70, 0x6b, 0x12, 0x39, 0x0a, 0x02, 0x66, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x44, 0x4c, 0x2e, 0x46, 0x4b, 0x52,
	0x02, 0x66, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x75, 0x6c, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6e, 0x75, 0x6c, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x1a, 0x58, 0x0a, 0x02, 0x46, 0x4b, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x1a, 0x34, 0x0a,
	0x0a, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x6c, 0x6c, 0x10, 0x00, 0x12, 0x0d, 0x0a,
	0x09, 0x4f, 0x6e, 0x6c, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a,
	0x4f, 0x6e, 0x6c, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a,
	0x4f, 0x6e, 0x6c, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x10, 0x04,
	0x12, 0x12, 0x0a, 0x0e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x6e, 0x64, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x10, 0x05, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x6e,
	0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x10, 0x06, 0x3a, 0x61, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xa1, 0x96, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x3a, 0x59, 0x0a, 0x05,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0xa2, 0x96, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x5c, 0x5a, 0x5a, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x69, 0x6b, 0x79, 0x61, 0x72, 0x75, 0x2d, 0x73, 0x75,
	0x7a, 0x75, 0x6b, 0x69, 0x2f, 0x67, 0x6f, 0x2d, 0x63, 0x6f, 0x6e, 0x2d, 0x32, 0x30, 0x32, 0x32,
	0x2d, 0x73, 0x70, 0x72, 0x69, 0x6e, 0x67, 0x2d, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x6d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_options_master_options_proto_rawDescOnce sync.Once
	file_server_options_master_options_proto_rawDescData = file_server_options_master_options_proto_rawDesc
)

func file_server_options_master_options_proto_rawDescGZIP() []byte {
	file_server_options_master_options_proto_rawDescOnce.Do(func() {
		file_server_options_master_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_options_master_options_proto_rawDescData)
	})
	return file_server_options_master_options_proto_rawDescData
}

var file_server_options_master_options_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_server_options_master_options_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_server_options_master_options_proto_goTypes = []interface{}{
	(MessageOption_AccessorType)(0),     // 0: server.options.master.MessageOption.AccessorType
	(FieldOption_AccessorType)(0),       // 1: server.options.master.FieldOption.AccessorType
	(*MessageOption)(nil),               // 2: server.options.master.MessageOption
	(*FieldOption)(nil),                 // 3: server.options.master.FieldOption
	(*MessageOption_DDL)(nil),           // 4: server.options.master.MessageOption.DDL
	(*MessageOption_DDL_Index)(nil),     // 5: server.options.master.MessageOption.DDL.Index
	(*FieldOption_DDL)(nil),             // 6: server.options.master.FieldOption.DDL
	(*FieldOption_Validation)(nil),      // 7: server.options.master.FieldOption.Validation
	(*FieldOption_DDL_FK)(nil),          // 8: server.options.master.FieldOption.DDL.FK
	(*descriptorpb.MessageOptions)(nil), // 9: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 10: google.protobuf.FieldOptions
}
var file_server_options_master_options_proto_depIdxs = []int32{
	0,  // 0: server.options.master.MessageOption.accessor_type:type_name -> server.options.master.MessageOption.AccessorType
	4,  // 1: server.options.master.MessageOption.ddl:type_name -> server.options.master.MessageOption.DDL
	1,  // 2: server.options.master.FieldOption.accessor_type:type_name -> server.options.master.FieldOption.AccessorType
	6,  // 3: server.options.master.FieldOption.ddl:type_name -> server.options.master.FieldOption.DDL
	7,  // 4: server.options.master.FieldOption.validations:type_name -> server.options.master.FieldOption.Validation
	5,  // 5: server.options.master.MessageOption.DDL.indexes:type_name -> server.options.master.MessageOption.DDL.Index
	8,  // 6: server.options.master.FieldOption.DDL.fk:type_name -> server.options.master.FieldOption.DDL.FK
	9,  // 7: server.options.master.message:extendee -> google.protobuf.MessageOptions
	10, // 8: server.options.master.field:extendee -> google.protobuf.FieldOptions
	2,  // 9: server.options.master.message:type_name -> server.options.master.MessageOption
	3,  // 10: server.options.master.field:type_name -> server.options.master.FieldOption
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	9,  // [9:11] is the sub-list for extension type_name
	7,  // [7:9] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_server_options_master_options_proto_init() }
func file_server_options_master_options_proto_init() {
	if File_server_options_master_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_options_master_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_options_master_options_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_options_master_options_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageOption_DDL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_options_master_options_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageOption_DDL_Index); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_options_master_options_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldOption_DDL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_options_master_options_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldOption_Validation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_options_master_options_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldOption_DDL_FK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_options_master_options_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_server_options_master_options_proto_goTypes,
		DependencyIndexes: file_server_options_master_options_proto_depIdxs,
		EnumInfos:         file_server_options_master_options_proto_enumTypes,
		MessageInfos:      file_server_options_master_options_proto_msgTypes,
		ExtensionInfos:    file_server_options_master_options_proto_extTypes,
	}.Build()
	File_server_options_master_options_proto = out.File
	file_server_options_master_options_proto_rawDesc = nil
	file_server_options_master_options_proto_goTypes = nil
	file_server_options_master_options_proto_depIdxs = nil
}
