// Code generated by protoc-gen-sample. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package clientcache

// キャラクター詳細
type CharacterDetail struct {
	// キャラクターID
	CharacterId string `json:"character_id"`
	// データ
	Data []byte `json:"data"`
}

type CharacterDetailSlice []*CharacterDetail
