// Code generated by protoc-gen-sample. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package clientcache

// キャラクター
type Character struct {
	// キャラクターID
	Id string `json:"id"`
	// データ
	Data []byte `json:"data"`
}

type CharacterSlice []*Character
