// Code generated by protoc-gen-sample. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package master

import (
	"time"

	"github.com/hikyaru-suzuki/go-con-2022-spring-sample/pkg/domain/enum"
)

// カード
type Card struct {
	// カードID
	ID string `json:"id,omitempty" validate:"required"`
	// キャラクターID
	CharacterID string `json:"character_id,omitempty" validate:"fk=Character_ID,required"`
	// 名前
	Name string `json:"name,omitempty" validate:"required"`
	// レアリティ
	Rarity enum.CardRarity `json:"rarity,omitempty" validate:"enum"`
	// アセットバンドルID
	AssetBundleID string `json:"asset_bundle_id,omitempty" validate:"required"`
	// 公開日
	PublishTime *time.Time `json:"publish_time,omitempty"`
	// 管理用メモ
	Memo string `json:"memo,omitempty"`
	// スキルパワー調整用係数
	SkillCoefficient int32 `json:"skill_coefficient,omitempty"`
	// マスタバージョン
	MasterVersion int32 `json:"master_version,omitempty" validate:"min=0"`
}
