// Code generated by protoc-gen-sample. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package master

// キャラクター
type Character struct {
	// キャラクターID
	ID string `json:"id,omitempty" validate:"required"`
	// 名前
	Name string `json:"name,omitempty" validate:"required"`
	// アセットバンドルID
	AssetBundleID string `json:"asset_bundle_id,omitempty" validate:"required"`
	// 表示順
	Order int32 `json:"order,omitempty" validate:"min=0"`
	// キャラクターストーリーのID一覧
	StoryIDs string `json:"story_ids,omitempty" validate:"fk-csv=Story_ID,min=0"`
	// マスタバージョン
	MasterVersion int32 `json:"master_version,omitempty" validate:"min=0"`
}
