// Code generated by protoc-gen-sample. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package master

// キャラクター詳細
type CharacterDetail struct {
	// キャラクターID
	CharacterID string `json:"character_id,omitempty" validate:"fk=Character_ID,required"`
	// 身長
	Height string `json:"height,omitempty" validate:"required"`
	// 体重
	Weight string `json:"weight,omitempty" validate:"required"`
	// マスタバージョン
	MasterVersion int32 `json:"master_version,omitempty" validate:"min=0"`
}
