// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: server/options/enums/options.proto

package enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumOption_AccessorType int32

const (
	EnumOption_Unknown         EnumOption_AccessorType = 0
	EnumOption_OnlyServer      EnumOption_AccessorType = 1
	EnumOption_ServerAndClient EnumOption_AccessorType = 2
)

// Enum value maps for EnumOption_AccessorType.
var (
	EnumOption_AccessorType_name = map[int32]string{
		0: "Unknown",
		1: "OnlyServer",
		2: "ServerAndClient",
	}
	EnumOption_AccessorType_value = map[string]int32{
		"Unknown":         0,
		"OnlyServer":      1,
		"ServerAndClient": 2,
	}
)

func (x EnumOption_AccessorType) Enum() *EnumOption_AccessorType {
	p := new(EnumOption_AccessorType)
	*p = x
	return p
}

func (x EnumOption_AccessorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumOption_AccessorType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_options_enums_options_proto_enumTypes[0].Descriptor()
}

func (EnumOption_AccessorType) Type() protoreflect.EnumType {
	return &file_server_options_enums_options_proto_enumTypes[0]
}

func (x EnumOption_AccessorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumOption_AccessorType.Descriptor instead.
func (EnumOption_AccessorType) EnumDescriptor() ([]byte, []int) {
	return file_server_options_enums_options_proto_rawDescGZIP(), []int{0, 0}
}

type EnumOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessorType EnumOption_AccessorType `protobuf:"varint,1,opt,name=accessor_type,json=accessorType,proto3,enum=server.options.enums.EnumOption_AccessorType" json:"accessor_type,omitempty"`
}

func (x *EnumOption) Reset() {
	*x = EnumOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_options_enums_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumOption) ProtoMessage() {}

func (x *EnumOption) ProtoReflect() protoreflect.Message {
	mi := &file_server_options_enums_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumOption.ProtoReflect.Descriptor instead.
func (*EnumOption) Descriptor() ([]byte, []int) {
	return file_server_options_enums_options_proto_rawDescGZIP(), []int{0}
}

func (x *EnumOption) GetAccessorType() EnumOption_AccessorType {
	if x != nil {
		return x.AccessorType
	}
	return EnumOption_Unknown
}

var file_server_options_enums_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*EnumOption)(nil),
		Field:         51001,
		Name:          "server.options.enums.enum",
		Tag:           "bytes,51001,opt,name=enum",
		Filename:      "server/options/enums/options.proto",
	},
}

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional server.options.enums.EnumOption enum = 51001;
	E_Enum = &file_server_options_enums_options_proto_extTypes[0]
)

var File_server_options_enums_options_proto protoreflect.FileDescriptor

var file_server_options_enums_options_proto_rawDesc = []byte{
	0x0a, 0x22, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x01, 0x0a,
	0x0a, 0x45, 0x6e, 0x75, 0x6d, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x52, 0x0a, 0x0d, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x40, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a,
	0x4f, 0x6e, 0x6c, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x6e, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x10,
	0x02, 0x3a, 0x54, 0x0a, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6e, 0x75, 0x6d,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb9, 0x8e, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x42, 0x5a, 0x5a, 0x58, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x69, 0x6b, 0x79, 0x61, 0x72, 0x75, 0x2d, 0x73, 0x75,
	0x7a, 0x75, 0x6b, 0x69, 0x2f, 0x67, 0x6f, 0x2d, 0x63, 0x6f, 0x6e, 0x2d, 0x32, 0x30, 0x32, 0x32,
	0x2d, 0x73, 0x70, 0x72, 0x69, 0x6e, 0x67, 0x2d, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x65,
	0x6e, 0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_options_enums_options_proto_rawDescOnce sync.Once
	file_server_options_enums_options_proto_rawDescData = file_server_options_enums_options_proto_rawDesc
)

func file_server_options_enums_options_proto_rawDescGZIP() []byte {
	file_server_options_enums_options_proto_rawDescOnce.Do(func() {
		file_server_options_enums_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_options_enums_options_proto_rawDescData)
	})
	return file_server_options_enums_options_proto_rawDescData
}

var file_server_options_enums_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_options_enums_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_server_options_enums_options_proto_goTypes = []interface{}{
	(EnumOption_AccessorType)(0),     // 0: server.options.enums.EnumOption.AccessorType
	(*EnumOption)(nil),               // 1: server.options.enums.EnumOption
	(*descriptorpb.EnumOptions)(nil), // 2: google.protobuf.EnumOptions
}
var file_server_options_enums_options_proto_depIdxs = []int32{
	0, // 0: server.options.enums.EnumOption.accessor_type:type_name -> server.options.enums.EnumOption.AccessorType
	2, // 1: server.options.enums.enum:extendee -> google.protobuf.EnumOptions
	1, // 2: server.options.enums.enum:type_name -> server.options.enums.EnumOption
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_server_options_enums_options_proto_init() }
func file_server_options_enums_options_proto_init() {
	if File_server_options_enums_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_options_enums_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_options_enums_options_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_server_options_enums_options_proto_goTypes,
		DependencyIndexes: file_server_options_enums_options_proto_depIdxs,
		EnumInfos:         file_server_options_enums_options_proto_enumTypes,
		MessageInfos:      file_server_options_enums_options_proto_msgTypes,
		ExtensionInfos:    file_server_options_enums_options_proto_extTypes,
	}.Build()
	File_server_options_enums_options_proto = out.File
	file_server_options_enums_options_proto_rawDesc = nil
	file_server_options_enums_options_proto_goTypes = nil
	file_server_options_enums_options_proto_depIdxs = nil
}
