// Code generated by protoc-gen-sample. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package transaction

import "time"

// ユーザー
type User struct {
	// ユーザーID
	UserID string
	// 公開ユーザーID
	PublicUserID string
	// 作成日時
	CreatedTime time.Time
	// 更新日時
	UpdatedTime time.Time
}
